export const services = [
    "Invitaciones",
    "Tarjetas (normales y con relieve)",
    "Folders Corp.",
    "Volantes",
    "Brochure",
    "Fotobooks",
    "Label para CD's",
    "Afiches/Bajantes",
    "Botones y Llaveros",
    "Catálogos",
    "Memorias",
    "Planos",
    "Carpetas",
    "Transfers",
    "Etiquetas/Troquelados (vinil y papel adhesivo)",
    "Calendarios Variados",
    "Carnets,Gafetes y Accesorios",
    "Ident. Corporativa",
    "Shoping",
    "Fundas",
    "Encuadernado",
    "Plastificados y Laminados",
    "Ampliaciones y Reducciones",
    "Folders",
    "sobres",
    "Diagramación",
    "T- shirts Bordados /Serigrafia / sublimado",
    "Gorras bordaddas",
    "Agenda personalizadas",
    "Tasas, Vasos, termos ",
    "Llaveros (acrilico, madera, PVC)",
    "Lapiceros",
    "Platos",
    "Alcancias ",

]